### ISSUE TITLE
Notification light does not work

### ISSUE THREAD

**Issue by OLDsheep** [zwliew/android_device_xiaomi_hm2014811#71] opened 2015-09-02 00:26 UTC
The notification light does not work, except when charging the device.

**Comment by pablosee** [comment] 2015-09-02 16:43
I can confirm that.

**Comment by zwliew** [comment] 2015-09-09 08:23
Fixed in September 5 release.

**Closed by zwliew** 2015-09-09 08:23 UTC
Labels: bug

**Comment by OLDsheep** [comment] 2015-09-09 11:41
in cm11

**Comment by zwliew** [comment] 2015-09-09 11:54
It doesn't? It worked for me.

**Comment by OLDsheep** [comment] 2015-09-09 11:54
only in the 2/8 build

**Comment by OLDsheep** [comment] 2015-09-09 12:03
Check this rom, it has no bugs: http://en.miui.com/thread-111502-1-1.html

**Comment by zwliew** [comment] 2015-09-09 12:03
Well revert to 2/8 build I guess. 2/8 build is more stable since 29/8 was just a stepping stone for integration with the open sourced kernel. I may or may not release a new CM 11.0 build to fix the existing bugs.
