### ISSUE TITLE
26/09 CM12.1: Black screen during call

### ISSUE THREAD

**Issue by teachmeluv** [zwliew/android_device_xiaomi_hm2014811#118] opened 2015-10-02 06:28 UTC
As some other users have reported in the xda thread the screen goes black during a call. It's not a fault from the proximity sensor as sensor tester has confirmed it's working. 
If you have headphones connected during a call the screen stays on. 
Most user own a Redmi 2 Prime (013 and 018).
Please have a look into that.

**Comment by ankitdb11** [comment] 2015-10-02 06:50
redmi 2 prime had no such issue. wat i think is dat this is a memory management issue mostly occuring with 1gb model when a user picks d call while he is doing more than moderate multitasking.

**Comment by teachmeluv** [comment] 2015-10-02 07:10
I have Redmi 2 Prime and I got that issue so "it has that issue". Even a con-argument are the 2GB Ram I have so your comment makes no sense to me.

**Comment by ankitdb11** [comment] 2015-10-02 07:20
model: 013 or 018??

**Comment by santosg23041993** [comment] 2015-10-03 13:05
Then what to do??

**Comment by watson96** [comment] 2015-10-11 04:16
Lol so this issue hasn't been closed? What happened to ROM dev-zwliew?

**Comment by zwliew** [comment] 2015-10-11 13:24
Duplicate of 95. This only happens on a few devices.

**Closed by zwliew** 2015-10-11 13:24 UTC

**Comment by Nipun2212** [comment] 2015-10-22 10:53
I am also facing the same problem of screen going blank during call...please help....
